name: mapfre
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - anyio=4.7.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=25.1.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attrs=24.3.0
  - babel=2.16.0
  - beautifulsoup4=4.13.5
  - blas=1.0=mkl
  - bleach=6.2.0
  - bottleneck=1.4.2
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.1
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.0
  - executing=2.2.1
  - expat=2.7.1
  - freetype=2.13.3
  - h11=0.16.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - idna=3.7
  - intel-openmp=2025.0.0
  - jinja2=3.1.6
  - jpeg=9f
  - json5=0.9.25
  - jsonschema=4.25.0
  - jsonschema-specifications=2023.7.1
  - lcms2=2.16
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libpng=1.6.39
  - libsodium=1.0.20
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.6
  - mistune=3.1.2
  - mkl=2025.0.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - nest-asyncio=1.6.0
  - numexpr=2.11.0
  - openjpeg=2.5.2
  - openssl=3.0.17
  - overrides=7.4.0
  - packaging=25.0
  - pandas=2.3.2
  - pandocfilters=1.5.1
  - parso=0.8.4
  - pillow=11.1.0
  - pip=25.2
  - platformdirs=4.3.7
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.43
  - psutil=7.0.0
  - pure_eval=0.2.3
  - pycparser=2.23
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.10.18
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - python-tzdata=2025.2
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - referencing=0.30.2
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - send2trash=1.8.2
  - setuptools=78.1.1
  - six=1.17.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.15
  - tomli=2.2.1
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.6
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1  # O la versi√≥n compatible con tu driver NVIDIA
  - faiss-gpu          # Necesario para el retriever
  - transformers       # Necesario para MetaCLIP
  - pip:
      - opencv-python-headless
      - decord           # Dependencia oculta de SAM3
      - timm             # Dependencia de modelos visuales
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - altair==5.5.0
      - annotated-types==0.7.0
      - astor==0.8.1
      - async-timeout==5.0.1
      - blinker==1.9.0
      - boto3==1.34.79
      - cachetools==6.2.0
      - click==8.3.0
      - cloudpickle==3.1.1
      - compressed-tensors==0.11.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - depyf==0.19.0
      - dill==0.4.0
      - diskcache==5.6.3
      - distro==1.9.0
      - einops==0.8.1
      - fastapi-cloud-cli==0.3.1
      - filelock==3.20.0
      - fonttools==4.60.0
      - frozendict==2.4.6
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gguf==0.17.1
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.27.0
      - google-api-python-client==2.185.0
      - google-auth==2.41.1
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.71.0
      - gputil==1.4.0
      - grpcio==1.76.0
      - grpcio-status==1.71.2
      - httplib2==0.31.0
      - httptools==0.7.1
      - huggingface-hub==0.35.3
      - interegular==0.3.3
      - jiter==0.11.1
      - kiwisolver==1.4.9
      - lark==1.2.2
      - lm-format-enforcer==0.11.3
      - markdown-it-py==4.0.0
      - matplotlib==3.10.6
      - mdurl==0.1.2
      - mistral-common==1.8.5
      - mpmath==1.3.0
      - msgspec==0.19.0
      - multidict==6.7.0
      - narwhals==2.6.0
      - networkx==3.4.2
      - ninja==1.13.0
      - numpy==2.2.6
      - openai==2.6.0
      - openai-harmony==0.0.4
      - opencv-python-headless==4.12.0.88
      - outlines-core==0.2.11
      - partial-json-parser==0.2.1.1.post6
      - perplexityai
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - py-cpuinfo==9.0.0
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.2
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pydantic-extra-types==2.10.6
      - pydeck==0.9.1
      - pyparsing==3.2.5
      - regex==2025.10.23
      - rich-toolkit==0.15.1
      - rignore==0.7.1
      - rsa==4.9.1
      - ruamel-yaml==0.18.15
      - ruamel-yaml-clib==0.2.14
      - safetensors==0.6.2
      - scipy==1.15.3
      - setproctitle==1.3.7
      - streamlit==1.50.0
      - sympy==1.14.0
      - tenacity==9.1.2
      - toml==0.10.2
      - torch==2.8.0
      - tqdm==4.67.1
      - transformers==4.57.1
      - typing-inspection==0.4.2
      - uritemplate==4.2.0
      - uvicorn==0.20.0
      - vllm==0.11.0
      - watchdog==6.0.0
      - watchfiles==1.1.1
      - websockets==15.0.1
      - yarl==1.22.0